In [2]:
import numpy as np
from time import process_time

In [3]:
python_list= [i for i in range(10000)]

start_time= process_time()

python_list= [i+5 for i in python_list]

end_time= process_time()

print(end_time - start_time)

0.0015812969999999815


In [4]:
np_array= np.array([i for i in range(10000)])

start_time= process_time()

np_array += 5

end_time= process_time()

print(end_time - start_time)

0.0004072520000000246


# Creating a arrays

In [5]:
a= np.array([1,2,3,4,5])
print(a)
print(type(a))
a.shape

[1 2 3 4 5]
<class 'numpy.ndarray'>


(5,)

In [6]:
b= np.array([(1,2,3,4,5),(6,7,8,9,0)])
print(b)
print(type(b))
b.shape

[[1 2 3 4 5]
 [6 7 8 9 0]]
<class 'numpy.ndarray'>


(2, 5)

In [7]:
c= np.array([(1,2,3,4,5),(6,7,8,9,0)],dtype= float)
print(c)
print(type(c))
c.shape

[[1. 2. 3. 4. 5.]
 [6. 7. 8. 9. 0.]]
<class 'numpy.ndarray'>


(2, 5)

# Inicial placeholders with zero

In [8]:
#Creating a array with zeros
x= np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
#Creating a array with ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
#Creating a array with perticular value
z= np.full((4,5),5)
print(z)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [11]:
#Creating a identity matrix
a= np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [12]:
#Creating a array with random values
b= np.random.random((3,4))
print(b)

[[0.90976647 0.71361707 0.75560729 0.72038672]
 [0.92082231 0.4712971  0.28900003 0.50921834]
 [0.95674042 0.70596626 0.09062506 0.87190001]]


In [16]:
#random integer value with in a specific value
c= np.random.randint(20,200,(5,4))
print(c)

[[ 44  46  96 139]
 [196 155  92 122]
 [ 42 101 100  94]
 [137 183 136 187]
 [ 59  45 108  34]]


In [21]:
#array of evenly spaced values
d= np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [25]:
#arrange of evenly spaced values --> specifing the step
e= np.arange(10,30,5)
print(e)

[10 15 20 25]


In [27]:
#convert a list to a numpy array
list2= [10,20,30,40,50]
np_array= np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

# Analysing the nparray

In [30]:
a= np.random.randint(10,90,(5,5))
print(a)
print("")
print(a.shape)

[[39 22 85 69 42]
 [70 77 81 24 56]
 [49 19 42 86 69]
 [50 38 29 59 86]
 [44 14 61 48 68]]

(5, 5)


In [33]:
#checking the number of diamentions
print(np.ndim(a))

2


In [34]:
#number of elements in an array
print(a.size)

25


In [35]:
#checking the datatype
print(a.dtype)

int64


# Mathematical operations on a np array

In [37]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,0]

print(list1 + list2) #concadinating or joins the two lists

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]


In [41]:
a= np.random.randint(10,20,(4,4))
b= np.random.randint(20,30,(4,4))

print(a)
print("")
print(b)
print("")
print(a+b)
print("")
print(a-b)
print("")
print(a*b)
print("")
print(a/b)

[[16 18 15 17]
 [19 10 13 15]
 [12 18 11 10]
 [14 17 14 15]]

[[20 25 27 20]
 [20 22 21 28]
 [22 23 28 23]
 [26 25 27 24]]

[[36 43 42 37]
 [39 32 34 43]
 [34 41 39 33]
 [40 42 41 39]]

[[ -4  -7 -12  -3]
 [ -1 -12  -8 -13]
 [-10  -5 -17 -13]
 [-12  -8 -13  -9]]

[[320 450 405 340]
 [380 220 273 420]
 [264 414 308 230]
 [364 425 378 360]]

[[0.8        0.72       0.55555556 0.85      ]
 [0.95       0.45454545 0.61904762 0.53571429]
 [0.54545455 0.7826087  0.39285714 0.43478261]
 [0.53846154 0.68       0.51851852 0.625     ]]


In [42]:
print(np.add(a,b))
print("")
print(np.subtract(a,b))
print("")
print(np.multiply(a,b))
print("")
print(np.divide(a,b))

[[36 43 42 37]
 [39 32 34 43]
 [34 41 39 33]
 [40 42 41 39]]

[[ -4  -7 -12  -3]
 [ -1 -12  -8 -13]
 [-10  -5 -17 -13]
 [-12  -8 -13  -9]]

[[320 450 405 340]
 [380 220 273 420]
 [264 414 308 230]
 [364 425 378 360]]

[[0.8        0.72       0.55555556 0.85      ]
 [0.95       0.45454545 0.61904762 0.53571429]
 [0.54545455 0.7826087  0.39285714 0.43478261]
 [0.53846154 0.68       0.51851852 0.625     ]]


# Array Manipulation

In [53]:
array = np.random.randint(0,10,(2,3))
print(array)
array.shape

[[3 4 2]
 [9 1 1]]


(2, 3)

In [54]:
#transpose
trans= np.transpose(array)
print(trans)
print("")
trans.shape

[[3 9]
 [4 1]
 [2 1]]



(3, 2)

In [55]:
array = np.random.randint(0,10,(2,3))
print(array)
array.shape

[[4 7 5]
 [2 0 3]]


(2, 3)

In [56]:
trans2= array.T
print(trans2)
print("")
print(trans2.shape)

[[4 2]
 [7 0]
 [5 3]]

(3, 2)


In [58]:
#reshaping an array
a= np.random.randint(0,10,(3,2))
print(a)
print("")
print(a.shape)

[[6 1]
 [4 5]
 [1 7]]

(3, 2)


In [62]:
b= a.reshape(2,3)
print(b)
print("")
print(b.shape)

[[6 1 4]
 [5 1 7]]

(2, 3)
